name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy MangoBot
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir app
            cd app
            git clone git@github.com:Marc-Cilliers/MangoBot .
            echo '✅ Deployed to Digital Ocean'
            pip3 install -r requirements.txt
            echo '✅ Packages installed'
            python3 mangobyte.py
            echo '✅ Bot running'
